spring:
  application:
    name: demo_springboot
  rabbitmq:
    host: 114.115.142.56
    port: 5672
    username: farbun
    password: noN{MIT16pt$7p.8zHeg
forest:
  variables: # 全局参数
    baseUrl: http://localhost:8080/user
server:
  port: 8888